#Max range of vent, high value CAN AND WILL cause lag.
ventRange = 2048
#Enables baby mode (Also known as ZAVODCHANIN mode, turns off oxygen requirements for vents)
enableBabyMode = false
#How many oxygen units in 1 mb
oxygenConsumption = 10
#Maximum radius of bubble generators
#Range: 5 ~ 20
bubbleMaxRadius = 5
#How many ticks (1 second ~ 20 ticks) for someone to IMPLODE from lack of air? Do not set lower than 15, or you may experience flicker.
timeToImplode = 10
#Enable Beyond Oxygen unbreathable dimensions
unbreathable_dimensions = true
#Enable Beyond Oxygen cold dimensions
cold_dimensions = true
#Enable Beyond Oxygen hot dimensions
hot_dimensions = true

